[package]
name = "faerie"
version = "0.0.2"
authors = ["m4b <m4b.github.io@gmail.com>"]
readme = "README.md"
keywords = ["elf", "mach-o", "binary", "object", "compiler"]
repository = "https://github.com/m4b/faerie"
license = "MIT"
description = "ELF and Mach-o native binary object file emitter"

[[bin]]
name = "prototype"
path = "src/bin/main.rs"

[dependencies]
goblin = "0.0.14"
scroll = "0.8"
log = "0.3.8"
env_logger = "0.4.3"
ordermap = "0.2.10"
structopt = "0.1.0"
structopt-derive = "0.1.0"
string-interner = "0.6.3"
failure = "0.1.0"
failure_derive = "0.1.0"
